remote_theme: chesterhow/tale

# Site settings
title:          Serious Coding Park
description:    "test description"
url:            "https://jinseriouspark.github.io/"

# Google Analytics
google_analytics: UAâ€”137863400-1

# Author
author:
  name:         Jinseul Park
  url:          www.linkedin.com/in/jinseulpark
  email:        jseulpark@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jinseriouspark